# Non Graded Challange 4

In [1]:
import numpy as np

In [6]:
# Soal no. 1
tensor_1 = [[[23,50],[7,12]],
            [[57,67],[99,43]],
            [[75,21],[57,12]],
            [[87,26],[18,84]]]

tensor_1 = np.array(tensor_1)
tensor_1

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [7]:
# soal no. 2
# Perkalian matriks

A = np.array([[23,50,19],
            [7,12,109],
            [57,67,98]])
B = np.array([17,22,19])

In [8]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [9]:
B

array([17, 22, 19])

In [10]:
A * B

array([[ 391, 1100,  361],
       [ 119,  264, 2071],
       [ 969, 1474, 1862]])

In [11]:
# Soal no. 3
# Lakukan Transpose, hitung determinan, dan inverse terhadap matriks

A = np.array([[23,50,19],
            [7,12,109],
            [57,67,98]])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [12]:
# Transpose
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [13]:
# Determinan
from numpy.linalg import det

B = det(A)
B

131344.0000000002

In [15]:
# Inverse
from numpy.linalg import inv

inverse_A = inv(A)
inverse_A

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])