# Non Grade 3 Week 2

1. Buatlah vektor di bawah ini dengan Python:
    17
    22
    19

In [1]:
import numpy as np

In [3]:
vect = np.array([17,22,19])
vect

array([17, 22, 19])

2. Diberikan 3 buah vector 3 dimensi:
        𝑨 =
        17
        22
        19
        ,𝑩 =
        10
        20
        11
        ,𝑪 =
        5
        12
        9
Hitunglah:
- A+B
- B-C
- A dot C
- A x B
- norm A
- Sudut antara vektor A dan B

In [4]:
vect_a = np.array([17,22,19])
vect_b = np.array([10,20,11])
vect_c = np.array([5,12,9])

In [5]:
# A - B
vect_a - vect_b

array([7, 2, 8])

In [6]:
# B - C
vect_b - vect_c

array([5, 8, 2])

In [7]:
# A dot C
vect_a.dot(vect_c)

520

In [8]:
# A x B
vect_a * vect_b

array([170, 440, 209])

In [9]:
# norm A
np.linalg.norm(vect_a)

33.67491648096547

In [11]:
# Sudut antara vektor A dan B
# cari cos_theta > radian > degree

cos_theta = (vect_a.dot(vect_b))/(np.linalg.norm(vect_a) * (np.linalg.norm(vect_b)))
cos_theta

0.9759590023331435

In [13]:
rad = np.arccos(cos_theta)
rad

0.21971776576153962

In [14]:
degree = np.degrees(rad)
degree

12.588900662180242