# Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.ones(2)

array([1., 1.])

In [15]:
np.empty(2) #nilai random?

array([1., 1.])

In [20]:
print(np.arange(0,10,2)) #(nilai awal, nilai akhir, step)
print(np.arange(1,11)) #(nilai awal, nilai akhir)
print(np.arange(3)) #(nilai terakhir) stepnya default 1

[0 2 4 6 8]
[ 1  2  3  4  5  6  7  8  9 10]
[0 1 2]


In [21]:
#kalkulasi dengan array
height = [1.45, 3.55, 7.96]
weight = [60.2, 34.2, 56.4]

np_height = np.array(height)
np_weight = np.array(weight)

perkalian = np_height * np_weight

print(perkalian)



[ 87.29  121.41  448.944]


## Add (append)

In [24]:
arr = np.array([1,2,3,4])
np.append(arr, 5)

array([1, 2, 3, 4, 5])

In [4]:
arr = np.array([1,2,3,4])
np.append(arr, [5,6,7])

array([1, 2, 3, 4, 5, 6, 7])

## Remove (delete)

In [9]:
arr = np.array([1,3,5,7])
np.delete(arr, 0) #yg dihilangin bagian indexnya

array([3, 5, 7])

## Sort

In [11]:
arr = np.array([3,4,2,7,1,9])
np.sort(arr)

array([1, 2, 3, 4, 7, 9])

## Dimesi

In [16]:
scalar = np.array(32)
print(scalar) #0D

32


In [22]:
array_1 = np.array([[1,2,3,4,5],
                    [6,7,8,9,10]]) #2D (ada 2 kurung siku)
                                    #kalau 3D (bikin 3 kurung siku)
print(array_1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
array_1.ndim #mengetahui dimensi sebuah matriks

2

In [24]:
array_1.size #berapa jumlah elemen yg didalam matriks

10

In [17]:
array_1.shape #(baris, kolom)

(2, 5)

In [25]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [26]:
b = a.reshape(3,2) #(3 baris, 2 kolom)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [28]:
a2 = a[np.newaxis] #convert dari 1D ke 2D
print(a2.shape)
print(a2)

(1, 6)
[[0 1 2 3 4 5]]


In [29]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [32]:
# You can use np.expand_dims to add an axis at index position 1 with:
b = np.expand_dims(a, axis=1) #axis 1 = kolom
print(b)
b.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

## Indexing and Slicing

In [33]:
data = np.array([1,2,3])
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [34]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a[a>=5])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 5  6  7  8  9 10 11 12]


In [36]:
# Ganjil Genap

divisible_by_1 = a[a%2==1] #ganjil
divisible_by_2 = a[a%2==0] #genap
print(divisible_by_1)
print(divisible_by_2)

[ 1  3  5  7  9 11]
[ 2  4  6  8 10 12]


In [37]:
#np.vstack() vertical
#np.hstack() horizontal

In [38]:
a = np.array([4,5,3,2])
a.sum()

14

In [54]:
b = np.array([[2,3],[4,2]])
b

array([[2, 3],
       [4, 2]])

In [55]:
print(b.sum(axis=0)) #sum the rows


[6 5]


In [56]:
print(b.sum(axis=1)) #sum the column

[5 6]


## Latihan

In [61]:
import numpy as np
x = np.arange(2,11).reshape(3,3)
print(x)
print(x.shape)
print(x.ndim)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
(3, 3)
2


In [62]:
arr = np.array(70)
print(arr)

70


In [63]:
arr = np.array([[1,2,3],[4,5,6],[4,5,6]])
print(arr)
arr.shape

[[1 2 3]
 [4 5 6]
 [4 5 6]]


(3, 3)

In [65]:
arr = np.array([[[1,2,3],
                [4,5,6]],
                [[1,2,3],
                [4,5,6]]])
print(arr)
arr.shape

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


(2, 2, 3)

In [70]:
array_tes = np.array([[3,7,10,2], [3,7,10,2]], ndmin=3) #ndmin = mengatur dimensi
print(array_tes)
print(array_tes.ndim)
print(array_tes.shape)

[[[ 3  7 10  2]
  [ 3  7 10  2]]]
3
(1, 2, 4)


In [71]:
array_tes = np.array([3,10,3,2])
print(array_tes[3] + array_tes[2])

5


In [76]:
arr = np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(arr[1,3]) #index ke 1, index ke 3 dalam index ke 1
arr.shape

4


(2, 5)

In [95]:
arr = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9], [10,11,12]]])

print(arr[:2, 0, 1])
print(arr.shape)
arr.ndim

[2 8]
(2, 2, 3)


3

In [97]:
arr = np.array([4,5,6,7,1,2,3])
print(arr[1:6:4])

[5 2]


In [98]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [99]:
def convert(fahr,kelv):
    cels = fahr * 1.8 + 32.0
    cels2 = kelv - 273.15
    return cels, cels2

print("Temperatur", convert(32,20))

Temperatur (89.6, -253.14999999999998)
