# Vector

besaran yang memiliki value dan arah

In [35]:
# create a vector
import numpy as np

In [36]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]

a + b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [37]:
# pake numpy
vect_a = np.array(a)
vect_b = np.array(b)
vect_a + vect_b

array([ 7,  9, 11, 13, 15])

## Vector Norm
suatu besaran yg menyatakan suatu panjang vektor-nya

In [38]:
# simbol vector norm || c ||

vect_a = np.array([3,4])
np.linalg.norm(vect_a) #pake L2 (Eulidean Distance)
np.linalg.norm(vect_a,1) # pake L1 (Manhattan Distance = dijumlahin vectornya)

7.0

Operasi Penjumlahan/Pengurangan/Pembagian

In [39]:
## Dengan bilangan
vect_a = np.array([1,2,3])
penjumlahan = vect_a + 2
pengurangan = vect_a - 2
pembagian = vect_a / 2

print(penjumlahan)
print(pengurangan)
print(pembagian)

[3 4 5]
[-1  0  1]
[0.5 1.  1.5]


In [40]:
## Antar Vector
b = [10,11,12]
vect_b = np.array(b)
vect_b

array([10, 11, 12])

In [41]:
vect_a + vect_b

array([11, 13, 15])

In [42]:
vect_a - vect_b

array([-9, -9, -9])

In [43]:
vect_a / vect_b

array([0.1       , 0.18181818, 0.25      ])

Operasi Perkalian

In [44]:
## Dengan Bilangan
vect_a = np.array([1,2,3])
vect_a * 2

array([2, 4, 6])

In [45]:
## Antar vector
vect_a = np.array([1,2,3])
vect_b = np.array([4,5,6])
vect_a * vect_b

array([ 4, 10, 18])

In [46]:
## DOT Product
vect_a.dot(vect_b) #vector a . vector b dot

32

In [47]:
np.dot(vect_a, vect_b)

32

In [48]:
vect_a@vect_b

32

Cosine Similarity

In [49]:
vect_f = np.array([4,0])
vect_g = np.array([6,0])

In [50]:
cos_theta = (vect_f.dot(vect_g))/ (np.linalg.norm(vect_f) * np.linalg.norm(vect_g))
cos_theta

# a . b = ||a|| ||b|| cos_theta
#cos_theta = a . b / ||a|| ||b||

1.0

In [51]:
rad = np.arccos(cos_theta) #radian
rad

0.0

In [52]:
degree = np.degrees(rad) #sudut => satuan derajat
degree

0.0

## Study Case

In [53]:
## Study Case 1

'''
text_1 = saya pergi ke rumah nenek saya
text_2 = saya pergi ke rumah kakek saya

'''

teks_1 = [2,1,1,1,1,0]
teks_2 = [2,1,1,1,0,1]

vect_t1 = np.array(teks_1)
vect_t2 = np.array(teks_2)

In [54]:
cos_theta = (vect_t1.dot(vect_t2)) / (np.linalg.norm(vect_t1) * np.linalg.norm(vect_t2))
cos_theta

# asumsi
# hasil theta => 0.5 => kurang mirip #treshold
# hasil theta => 0.8 => agak mirip
# hasil theta => 1 => mirip

0.8749999999999998

In [55]:
## Study Case 2

'''
teks_3 = Selamat pagi dunia
teks_4 = Nusantara ibu kota baru

'''

teks_3 = [1,1,1,0,0,0,0]
teks_4 = [0,0,0,1,1,1,1]

vect_t3 = np.array(teks_3)
vect_t4 = np.array(teks_4)

In [56]:
cos_theta = (vect_t3.dot(vect_t4)) / (np.linalg.norm(vect_t3) * np.linalg.norm(vect_t4))
cos_theta

0.0