# Matrix

- memungkinkan menyimpan vektor
- adalah 2 dimensional array yg memiliki baris dan kolom

In [75]:
# dimensi array
# [1,2,3] -> array 1D
# [[1,2][3,4][5,6]] -> array 2D

In [76]:
import numpy as np

In [77]:
data_1 = [1,2,3] # array 1 dimensi
data_2 = [[1,2,3], [4,5]] # array 2 dimensi tapi contoh ini bukan matriks
data_3 = [[1,2,3],[4,5,6]] # array 2 dimensi 

In [78]:
vect_1 = np.array(data_1)
vect_1

array([1, 2, 3])

In [79]:
data2 = np.array(data_2)
data2

C:\Users\Acer Nitro 5\AppData\Local\Temp\ipykernel_16708\343561765.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data2 = np.array(data_2)


array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [80]:
data3 = np.array(data_3)
data3

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
# definisi matriks
data1 = [[1,2],[3,4],[5,6],[7,8]] # pastikan jumlah elemen di list dalam sama
data_mat = np.array(data1)
data_mat

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## Type Matrix

## Operasi Matriks

- Operasi Penjumlahan dan Pengurangan Matriks

In [82]:
# Operasi penjumlahan & Pengurangan matriks

A = [[1,2,3],
        [4,5,6],
        [7,8,9]]
A = np.array(A)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
B = [[7,8,9],
        [9,8,7],
        [1,2,3]]

B = np.array(B)
B

array([[7, 8, 9],
       [9, 8, 7],
       [1, 2, 3]])

In [84]:
A + B

array([[ 8, 10, 12],
       [13, 13, 13],
       [ 8, 10, 12]])

In [85]:
A - B

array([[-6, -6, -6],
       [-5, -3, -1],
       [ 6,  6,  6]])

- Perkalian Matriks dan Scalar

In [86]:
# Perkalian matriks dan scalar
# 3 * A
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
3 * A

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [88]:
# Perkalian Hadamard product (element wise)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
B

array([[7, 8, 9],
       [9, 8, 7],
       [1, 2, 3]])

In [90]:
A * B

array([[ 7, 16, 27],
       [36, 40, 42],
       [ 7, 16, 27]])

- Matriks - Matriks Multiplication

In [91]:
# matrix - matrix multiplication
A = [[1,2],
    [3,4]] # 2x2
B = [[2,1],
    [3,2]] # 2x2
A = np.array(A)
B = np.array(B)

In [92]:
A @ B # matrix - to matrix multiplication

array([[ 8,  5],
       [18, 11]])

In [93]:
np.dot(A,B)

array([[ 8,  5],
       [18, 11]])

In [94]:
A = [[1,2],
    [3,4],
    [5,6]]
A = np.array(A)
A # 3x2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [95]:
B = [[5,6,7],
    [8,9,3]]
B = np.array(B)
B # 2 x 3

array([[5, 6, 7],
       [8, 9, 3]])

In [96]:
A @ B

array([[21, 24, 13],
       [47, 54, 33],
       [73, 84, 53]])

- Matriks Transpose

In [97]:
C = [[1,2],[3,4],[5,6]]
C = np.array(C)
C

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
C.T # baris menjadi kolom, kolom jadi baris

array([[1, 3, 5],
       [2, 4, 6]])

- Inverse

In [99]:
A = [[1,2],[7,8]]
A = np.array(A)
A

array([[1, 2],
       [7, 8]])

In [100]:
from numpy.linalg import inv # import inverse dari library numpy

In [101]:
inv_A = inv(A)
inv_A

array([[-1.33333333,  0.33333333],
       [ 1.16666667, -0.16666667]])

In [102]:
A @ inv_A

array([[1., 0.],
       [0., 1.]])

In [103]:
inv_A @ A

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

Ga semua matriks yg punya inverse-nya. 
Contohnya : matriks singular

- Determinan

In [104]:
from numpy.linalg import det

In [105]:
A = ([1,2,3], [2,5,7],[3,7,9])
A = np.array(A)
A

array([[1, 2, 3],
       [2, 5, 7],
       [3, 7, 9]])

In [106]:
B = det(A)
B

# determinan = 0, tidak memiliki inverse
# determinan =! 0, punya inverse

-0.9999999999999991

- Tensor

In [107]:
A = np.array([[1,2],[3,7]])
B = np.array([[1,1],[1,1]])

In [108]:
tensor = [A, B]
tensor = np.array(tensor)
tensor

array([[[1, 2],
        [3, 7]],

       [[1, 1],
        [1, 1]]])

In [109]:
tensor.shape
# ada 2 matriks dengan ukuran 2x2 didalam tensor

(2, 2, 2)

In [110]:
A = np.array([[1,2],[3,7],[3,3]])
B = np.array([[1,1],[1,1],[4,9]])

In [111]:
tensor = [A, B]
tensor = np.array(tensor)
tensor

array([[[1, 2],
        [3, 7],
        [3, 3]],

       [[1, 1],
        [1, 1],
        [4, 9]]])

In [112]:
tensor.shape

(2, 3, 2)

In [113]:
# vector -> 1D array
# matriks -> 2D array
# lebih dari 2D -> n-D -> tensor